
version: '3'
services:
  web:
    build: .
    ports:
     - "3030:3030"
    depends_on: 
     - redis
  # Redis is not used but in the template but you will probably need it
  redis:
    image: "redis:alpine"